
export const PRODUCTS =[
   {"title":'Food',
   "items":[
    {
        "id":1,
        "name": "Fajitas",
        "imageUrl": "https://www.linkpicture.com/q/f1.jpg",
        "price": 50,
        "star":4.5,
    },
    {
        "id":2,
        "name": "Jerky",
        "imageUrl": "https://www.linkpicture.com/q/f2.jpg",
        "price": 40,
        "star":4.3,
    },
    {
        "id":3,
        "name": "Twinkies",
        "imageUrl": "https://www.linkpicture.com/q/f3.jpg",
        "price": 50,
        "star":4.4,
    },
    {
        "id":4,
        "name": "Pot roast",
        "imageUrl": "https://www.linkpicture.com/q/f5_2.jpg",
        "price": 70,
        "star":4.8,
    },
    {
        "id":5,
        "name": "Jambalaya",
        "imageUrl": "https://www.linkpicture.com/q/f6_3.jpg",
        "price": 60,
        "star":4.6,
    },
    {
        "id":6,
        "name": "Smithfied ham",
        "imageUrl": "https://www.linkpicture.com/q/f7_1.jpg",
        "price": 30,
        "star":5,
    },
    {
        "id":7,
        "name": "Meatloaf",
        "imageUrl": "https://www.linkpicture.com/q/f9.jpg",
        "price": 65,
        "star":4.8,
    },
    {
        "id":8,
        "name": "Grits",
        "imageUrl": "https://www.linkpicture.com/q/f10_1.jpg",
        "price": 45,
        "star":2.7,
    },
    {
        "id":9,
        "name": "Crab cakes",
        "imageUrl": "https://www.linkpicture.com/q/f11.jpg",
        "price": 37,
        "star":3.9,
    },
    {
        "id":10,
        "name": "Cioppino",
        "imageUrl": "https://www.linkpicture.com/q/f12_1.jpg",
        "price": 18,
        "star":4.6,
    }
]
},
{ 'title':'Shoe',
'items': [
    {
        'id':11,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/s1_16.jpg',
        "price":51,
        'star':4.8,
    },
    {
        'id':12,
        'name': 'bt',
        'imageUrl':'https://www.linkpicture.com/q/s2_10.jpg',
        "price":56,
        'star':4.2,
    },
    {
        'id':13,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/s3_2.jpg',
        "price":70,
        'star':4.6,
    },
    {
        'id':14,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/s4_2.jpg',
        "price":72,
        'star':4.9,
    },
    {
        'id':15,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/s5_1.jpg',
        "price":50,
        'star':4.6,
    },
    {
        'id':16,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/s6_3.jpg',
        "price":50,
        'star':4.6,
    },
    {
        'id':17,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/s7_3.jpg',
        "price":50,
        'star':4.6,
    },
    {
        'id':18,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/s8_5.jpg',
        "price":50,
        'star':4.6,
    },
    {
        'id':19,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/s9_2.jpg',
        "price":50,
        'star':4.6,
    },
    {
        'id':20,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/s10_1.jpg',
        "price":50,
        'star':4.6,
    },
    {
        'id':21,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/s13_1.jpg',
        "price":50,
        'star':4.6,
    },
    {
        'id':22,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/s14_1.jpg',
        "price":50,
        'star':4.6,
    },
    {
        'id':23,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/s16.jpg',
        "price":50,
        'star':4.6,
    },
    {
        'id':24,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/s17_1.jpg',
        "price":50,
        'star':4.6,
    },
    {
        'id':25,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/s18_1.jpg',
        "price":50,
        'star':4.6,
    },
    {
        'id':26,
        'name': 'bronche',
        'imageUrl':'hhttps://www.linkpicture.com/q/s19_1.jpg',
        "price":50,
        'star':4.6,
    },
    {
        'id':27,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/s20.jpg',
        "price":50,
        'star':4.6,
    },
    {
        'id':28,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/s21_1.jpg',
        "price":50,
        'star':4.6,
    },
    {
        'id':29,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/s22_1.jpg',
        "price":50,
        'star':4.6,
    },
    {
        'id':30,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/s23_1.jpg',
        "price":50,
        'star':4.6,
    },
    {
        'id':31,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/s24_2.jpg',
        "price":50,
        'star':4.6,
    },
    {
        'id':32,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/s25_1.jpg',
        "price":50,
        'star':4.6,
    },
    {
        'id':33,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/s26_1.jpg',
        "price":50,
        'star':4.6,
    },
    {
        'id':34,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/s27_3.jpg',
        "price":50,
        'star':4.6,
    },
    {
        'id':35,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/s29_1.jpg',
        "price":50,
        'star':4.6,
    },
]

},
{
    "title":"burger",
    "items":[
        {
        'id':36,
        'name': 'bruch',
        'imageUrl':'https://www.linkpicture.com/q/b2_16.png',
        "price":54,
        'star':4.7,
    },
    {
        'id':37,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b3_12.png',
        "price":50,
        'star':4.6,
    },
    {
        'id':38,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b4_13.png',
        "price":50,
        'star':4.6,
    },
    {
        'id':39,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b5_12.png',
        "price":50,
        'star':4.6,
    },
    {
        'id':40,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b7_7.png',
        "price":50,
        'star':4.6, 
    },{
        'id':41,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b1_17.png',
        "price":50,
        'star':4.6, 
    },{
        'id':42,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b3_12.png',
        "price":50,
        'star':4.6, 
    },{
        'id':43,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b8_9.png',
        "price":50,
        'star':4.6, 
    },{
        'id':44,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b9_8.png',
        "price":50,
        'star':4.6, 
    },{
        'id':45,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b10_5.png',
        "price":50,
        'star':4.6, 
    },{
        'id':46,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b11_7.png',
        "price":50,
        'star':4.6, 
    },{
        'id':47,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b12_5.png',
        "price":50,
        'star':4.6, 
    },{
        'id':48,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b13_7.png',
        "price":50,
        'star':4.6, 
    },{
        'id':49,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b14_6.png',
        "price":50,
        'star':4.6, 
    },{
        'id':50,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b15_7.png',
        "price":50,
        'star':4.6, 
    },{
        'id':51,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b16_4.png',
        "price":50,
        'star':4.6, 
    },{
        'id':52,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b18_4.png',
        "price":50,
        'star':4.6, 
    },{
        'id':53,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b19_4.png',
        "price":50,
        'star':4.6, 
    },{
        'id':54,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b20_3.png',
        "price":50,
        'star':4.6, 
    },
    {
        'id':55,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b21_1.png',
        "price":50,
        'star':4.6, 
    },
    {
        'id':55,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b22_1.png',
        "price":50,
        'star':4.6, 
    },
    {
        'id':55,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b23.png',
        "price":50,
        'star':4.6, 
    },
    {
        'id':56,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b24.png',
        "price":50,
        'star':4.6, 
    },{
        'id':57,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b25.png',
        "price":50,
        'star':4.6, 
    },
    {
        'id':58,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b26.png',
        "price":50,
        'star':4.6, 
    },
    {
        'id':59,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b27.png',
        "price":50,
        'star':4.6, 
    },
    {
        'id':60,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b30.png',
        "price":50,
        'star':4.6, 
    },
    {
        'id':61,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b31.png',
        "price":50,
        'star':4.6, 
    },
    {
        'id':62,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b32.png',
        "price":50,
        'star':4.6, 
    },
    {
        'id':63,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b34.png',
        "price":50,
        'star':4.6, 
    },
    {
        'id':64,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b35.png',
        "price":50,
        'star':4.6, 
    },
    {
        'id':65,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b36.png',
        "price":50,
        'star':4.6, 
    },
    {
        'id':66,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b37.png',
        "price":50,
        'star':4.6, 
    },
    {
        'id':67,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b38.png',
        "price":50,
        'star':4.6, 
    },
    {
        'id':68,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/b39.png',
        "price":50,
        'star':4.6, 
},
{
    'id':69,
    'name': 'bronche',
    'imageUrl':'https://www.linkpicture.com/q/b39.png',
    "price":50,
    'star':4.6, 
}

]
},
{
 "title":"Watches",
 "items":[
    {
        'id':70,
        'name': 'watch',
        'imageUrl':'https://www.linkpicture.com/q/1-2_10.jpg',
        "price":50,
        'star':4.6, 
    },
    {
        'id':71,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/3_9.jpg',
        "price":50,
        'star':4.6, 
    },
    {
        'id':72,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/5_8.jpg',
        "price":50,
        'star':4.6, 
    },
    {
        'id':73,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/6_140.jpg',
        "price":50,
        'star':4.6, 
    },
    {
        'id':74,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/7_55.jpg',
        "price":50,
        'star':4.6, 
    },
    {
        'id':75,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/8_53.jpg',
        "price":50,
        'star':4.6, 
    },
    {
        'id':76,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/10_57.jpg',
        "price":50,
        'star':4.6, 
    },
    {
        'id':77,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/11_199.jpg',
        "price":50,
        'star':4.6, 
    },
    {
        'id':78,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/12_174.jpg',
        "price":50,
        'star':4.6, 
    },
    {
        'id':79,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/13_47.jpg',
        "price":50,
        'star':4.6, 
    },
    {
        'id':80,
        'name': 'bronche',
        'imageUrl':'https://www.linkpicture.com/q/14_107.jpg',
        "price":50,
        'star':4.6, 
    },
{
    'id':81,
    'name': 'bronche',
    'imageUrl':'https://www.linkpicture.com/q/15_112.jpg',
    "price":50,
    'star':4.6, 
},
{
    'id':82,
    'name': 'bronche',
    'imageUrl':'https://www.linkpicture.com/q/16_111.jpg',
    "price":50,
    'star':4.6, 
},
{
    'id':83,
    'name': 'bronche',
    'imageUrl':'https://www.linkpicture.com/q/b39.png',
    "price":50,
    'star':4.6, 
},
{
    'id':84,
    'name': 'bronche',
    'imageUrl':'https://www.linkpicture.com/q/18_29.jpg',
    "price":50,
    'star':4.6, 
},
{
    'id':85,
    'name': 'bronche',
    'imageUrl':'https://www.linkpicture.com/q/19_86.jpg',
    "price":50,
    'star':4.6, 
},
{
    'id':86,
    'name': 'bronche',
    'imageUrl':'https://www.linkpicture.com/q/20_14.jpg',
    "price":50,
    'star':4.6, 
},
{
    'id':87,
    'name': 'bronche',
    'imageUrl':'https://www.linkpicture.com/q/21_11.jpg',
    "price":50,
    'star':4.6, 
},
{
    'id':88,
    'name': 'bronche',
    'imageUrl':'https://www.linkpicture.com/q/22_17.jpg',
    "price":50,
    'star':4.6, 
},
{
    'id':89,
    'name': 'bronche',
    'imageUrl':'https://www.linkpicture.com/q/23_74.jpg',
    "price":50,
    'star':4.6, 
},
{
    'id':90,
    'name': 'bronche',
    'imageUrl':'https://www.linkpicture.com/q/24_13.jpg',
    "price":50,
    'star':4.6, 
},
{
    'id':91,
    'name': 'bronche',
    'imageUrl':'https://www.linkpicture.com/q/25_58.jpg',
    "price":50,
    'star':4.6, 
},
{
    'id':92,
    'name': 'bronche',
    'imageUrl':'https://www.linkpicture.com/q/26_7.jpg',
    "price":50,
    'star':4.6, 
},
{
    'id':92,
    'name': 'bronche',
    'imageUrl':'https://www.linkpicture.com/q/27_10.jpg',
    "price":50,
    'star':4.6, 
},
{
    'id':93,
    'name': 'bronche',
    'imageUrl':'https://www.linkpicture.com/q/29_10.jpg',
    "price":50,
    'star':4.6, 
},
{
    'id':94,
    'name': 'bronche',
    'imageUrl':'https://www.linkpicture.com/q/30_10.jpg',
    "price":50,
    'star':4.6, 
},
{
    'id':95,
    'name': 'bronche',
    'imageUrl':'https://www.linkpicture.com/q/31_9.jpg',
    "price":50,
    'star':4.6, 
},
{
    'id':96,
    'name': 'bronche',
    'imageUrl':'https://www.linkpicture.com/q/32_10.jpg',
    "price":50,
    'star':4.6, 
},
{
    'id':97,
    'name': 'bronche',
    'imageUrl':'https://www.linkpicture.com/q/33_9.jpg',
    "price":50,
    'star':4.6, 
},
{
    'id':98,
    'name': 'bronche',
    'imageUrl':'https://www.linkpicture.com/q/34_4.jpg',
    "price":50,
    'star':4.6, 
},
{
    'id':99,
    'name': 'bronche',
    'imageUrl':'https://www.linkpicture.com/q/35_27.jpg',
    "price":50,
    'star':4.6, 
},
{
    'id':100,
    'name': 'bronche',
    'imageUrl':'https://www.linkpicture.com/q/36_29.jpg',
    "price":50,
    'star':4.6, 
},
{
    'id':101,
    'name': 'bronche',
    'imageUrl':'https://www.linkpicture.com/q/37_39.jpg',
    "price":50,
    'star':4.6, 
},
{
    'id':96,
    'name': 'bronche',
    'imageUrl':'https://www.linkpicture.com/q/smartwatch-mockup_92914-354.jpg',
    "price":50,
    'star':4.6, 
}
 ]   
}
]